map $http_x_forwarded_proto $contabilidade_forwarded_proto {
  default $http_x_forwarded_proto;
  "" $scheme;
}

map $http_x_forwarded_port $contabilidade_forwarded_port {
  default $http_x_forwarded_port;
  "" $server_port;
}

server {
  listen 8080;
  server_name _;

  client_max_body_size 27m;

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location /api/ {
    proxy_pass http://backend:8080;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $contabilidade_forwarded_proto;
    proxy_set_header X-Forwarded-Port $contabilidade_forwarded_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Correlation-Id $http_x_correlation_id;
  }

  location /auth/ {
    proxy_pass http://keycloak:8080/auth/;
    proxy_http_version 1.1;
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Proto $contabilidade_forwarded_proto;
    proxy_set_header X-Forwarded-Port $contabilidade_forwarded_port;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
